apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-flying-egret
    devEnvApprovers:
    - todo
    dockerRegistryOrg: oci
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "968453465120"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: softcell-test-447106
    provider: gke
    registry: us-central1-docker.pkg.dev/softcell-test-447106
    zone: us-central1-a
  environments:
  - key: dev
    owner: nikolinmajmari
    repository: google-cloud-jenkinx-cluster-repo-1
  - key: staging
  - key: production
  ingress:
    domain: ""
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  pipelineUser:
    username: nikolinmajmari
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-flying-egret-8d10da0bcc8d
  - name: reports
    url: gs://reports-tf-jx-flying-egret-8d10da0bcc8d
  - name: repository
    url: gs://repository-tf-jx-flying-egret-8d10da0bcc8d
  vault: {}
  webhook: lighthouse
